### PR TITLE
Add routing, refactor to functional components and hooks, rearrange folder structure

### PR DESCRIPTION
**Pull request by pranavmodx**

### CODE REVIEW

**Comment by athul** [comment]
Ran this locally, with 2 browsers obv, But was unable to load info. I have got about a minimum of 15 no-peers available logs. @subins2000 could you look into this.

Love the new design BTW

**Comment by subins2000** [comment]
Design is good !

I've checked it, but there are some issues which I've told @pranavmodx about :

* startClient() should only be called once
* which brings all the other problems together with it

**Comment by pranavmodx** [comment]
I have moved the `p2wiki` instantiation and calling of `startClient()` from `Search` to the `ClientPage` component. This ensures it's only called once during the rendering. 
**Reason** : `Search` re-renders on every state change. So it calls `startClient()` also multiple times in the process.

**Comment by subins2000** [comment]
@pranavmodx Good, it fixes the `startClient()` issues :tada: 

The rendering of result is heavy, cause images are altered to load from torrent. We need to only render that once and not re-render everytime user enters something in the query box. Perhaps separating the form to `<SearchForm>` component and pass the query once submit to parent `<Search>`

Also, would be better if `<Result>` is separated along with `createMarkup()` function. We need to minimise the render of result

**Comment by pranavmodx** [comment]
I moved the `SearchForm` and `Result` into separate components. 
Also moved `createMarkup()` to `getFromWiki()`. Now, `createMarkup()` is called only on hitting submit. So it's not rendered each time input query is changed like before.
Hopefully, this should fix it.

**Pull request merged**
